[illumos] switch waker impl back to being pipe-based
In
https://github.com/tokio-rs/mio/commit/1133ed006b9e2a6dcf27edcdf54309ce648c3a15,
it looks like the waker implementation on illumos (perhaps inadvertently) got
switched from being pipe-based to being eventfd-based. Unfortunately, the
eventfd impl seems to break the `waker_multiple_wakeups_different_thread` on illumos:

```
thread 'waker_multiple_wakeups_different_thread' panicked at tests/waker.rs:157:5:
assertion failed: !events.is_empty()
```

While we separately figure out what might be going wrong in the eventfd impl,
it's worth switching back to the old pipe-based impl which is known to work,
and which does fix this test.